version: '3'
services:
  envoy-users-v2:
    build:
        context: .
        dockerfile: Dockerfile-envoy
    command: ["envoy", "-c", "/etc/envoy/sidecar.yaml"]
    ports:
      - "80:9000"   # expose ingress
      - "9901:9901" # expose admin

  users-v2:
    build: .
    command: ["users-v2", "-w", "envoy-users-v2:9100"] # sidecar egress

  widgets-v1:
    build: .
    command: ["widgets-v1"]

  prometheus:
    build:
        context: .
        dockerfile: Dockerfile-prometheus
    ports:
      - "9090:9090"

  xds:
    build: .
    command: ["xds-docker"]
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro